-- Clases impartidas por Fran, con su nombre, apellido, clase, descripción y fecha de inicio.
SELECT P.NOMBRE AS "Nombre",
    P.APELLIDO1 AS "Apellido1",
       P.APELLIDO2 AS "Apellido2",
    C.NOMBRE AS "Clase", 
    C.DESCRIPCION AS "Descripción", 
    C.FECHA_INICIO AS "Fecha de Inicio"
FROM CLASE C
JOIN MONITOR_CLASE MC ON C.ID_CLASE = MC.ID_CLASE
JOIN MONITOR M ON MC.ID_MONITOR = M.ID_MONITOR
JOIN EMPLEADO E ON M.ID_EMPLEADO = E.ID_EMPLEADO
JOIN PERSONA P ON E.DNI = P.DNI
WHERE UPPER(P.NOMBRE) LIKE '%FRAN%';




-- Nombre completo de los monitores y salario, ordenados por salario.
SELECT P.NOMBRE || ' ' || P.APELLIDO1 || ' ' || NVL(P.APELLIDO2, '') AS "Nombre Completo", 
       SUM(E.SALARIO) AS "Salario"
FROM PERSONA P
JOIN EMPLEADO E ON P.DNI = E.DNI
JOIN MONITOR M ON E.ID_EMPLEADO = M.ID_EMPLEADO
GROUP BY P.NOMBRE, P.APELLIDO1, P.APELLIDO2
ORDER BY "Salario" DESC;



-- Nombre de los usuarios y lasrutinas que tienen.
SELECT P.NOMBRE AS USUARIO,
    R.NOMBRE AS RUTINA,
    R.DESCRIPCION
FROM PERSONA P
JOIN USUARIO U ON P.DNI = U.DNI
JOIN USUARIO_RUTINA UR ON U.ID_USUARIO = UR.ID_USUARIO
JOIN RUTINA R ON UR.ID_RUTINA = R.ID_RUTINA;


-- Mostrar los datos de contacto de los usuarios
SELECT P.NOMBRE AS USUARIO,
P.APELLIDO1 AS "Apellido",
T.NUMERO AS TELEFONO,
P.EMAIL
FROM PERSONA P
JOIN TELEFONO T ON P.DNI = T.DNI
JOIN USUARIO U ON P.DNI = U.DNI;



-- Usuarios que están inscritos en la misma rutina.
SELECT E.NOMBRE AS EJERCICIO, 
COUNT(RE.ID_RUTINA) AS FRECUENCIA
FROM EJERCICIO E
JOIN RUTINA_EJERCICIO RE ON E.ID_EJERCICIO = RE.ID_EJERCICIO
GROUP BY E.ID_EJERCICIO, E.NOMBRE
ORDER BY FRECUENCIA DESC;


