-- 1. Primero eliminar tablas con relaciones many-to-many (más dependientes)
DROP TABLE MONITOR_CLASE CASCADE CONSTRAINTS;
DROP TABLE USUARIO_RUTINA CASCADE CONSTRAINTS;
DROP TABLE RUTINA_EJERCICIO CASCADE CONSTRAINTS;

-- 2. Luego tablas que tienen claves foráneas
DROP TABLE CLASE CASCADE CONSTRAINTS;
DROP TABLE MONITOR CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE HORARIO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE TELEFONO CASCADE CONSTRAINTS;

-- 3. Finalmente tablas independientes
DROP TABLE RUTINA CASCADE CONSTRAINTS;
DROP TABLE EJERCICIO CASCADE CONSTRAINTS;
DROP TABLE SALA CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;
    
    
    
    CREATE TABLE PERSONA(
        DNI VARCHAR2(20) PRIMARY KEY,
        NOMBRE VARCHAR2(20) NOT NULL,
        APELLIDO1 VARCHAR2(30) NOT NULL,
        APELLIDO2 VARCHAR2(30),
        DIRECCION VARCHAR2(100) NOT NULL,
        EMAIL VARCHAR2(100) UNIQUE,
        CUENTA_BANCARIA VARCHAR2(100),
        FECHA_NAC DATE
        
       
    );
    CREATE TABLE TELEFONO(
        ID_TELEFONO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        DNI VARCHAR2(20),
        NUMERO VARCHAR2(20) NOT NULL,
        TIPO VARCHAR2(20) CHECK (TIPO IN('MOVIL','TRABAJO','CASA')),
        
        CONSTRAINT FK_TELEFONO FOREIGN KEY (DNI)
        REFERENCES PERSONA(DNI)
    );
    
    
    
    
    CREATE TABLE EMPLEADO(
        ID_EMPLEADO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        DNI VARCHAR2(20),
        SALARIO NUMBER(10,2),
        FECHA_CONTRATACION DATE,
        
        CONSTRAINT FK_EMPLEADO FOREIGN KEY (DNI)
        REFERENCES PERSONA(DNI)
        
    );
    
    CREATE TABLE HORARIO(
        ID_HORARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        ID_EMPLEADO NUMBER(10),
        TIPO VARCHAR2(1) CHECK(TIPO IN ('M','T')),
        CONSTRAINT FK_HORARIO FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO (ID_EMPLEADO)
    );
    
    CREATE TABLE MONITOR(
        ID_MONITOR NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        ID_EMPLEADO NUMBER(10),
        
        CONSTRAINT FK_MONITOR FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO(ID_EMPLEADO)
    );
    
    
    CREATE TABLE RUTINA (
        ID_RUTINA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR2(30) UNIQUE,
        DESCRIPCION VARCHAR2(100)
    );
    
    CREATE TABLE USUARIO(
        ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        DNI VARCHAR2(20),
        
        CONSTRAINT FK_USUARIO FOREIGN KEY (DNI)
        REFERENCES PERSONA (DNI)
    );
    
    CREATE TABLE USUARIO_RUTINA(
        ID_RUTINA NUMBER(10),
        ID_USUARIO NUMBER(10),
        
        
        
        CONSTRAINT FK_USUARIO_RUTINA FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO),
        
        CONSTRAINT FK_RUTINA_USUARIO FOREIGN KEY (ID_RUTINA)
        REFERENCES RUTINA(ID_RUTINA),
        
        CONSTRAINT PK_USUARIO_RUTINA PRIMARY KEY(ID_RUTINA,ID_USUARIO)
       
    );
    CREATE TABLE EJERCICIO(
        ID_EJERCICIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR2(50) NOT NULL UNIQUE,
        DESCRIPCION VARCHAR2(200),
        GRUPO_MUSCULAR VARCHAR2(50) NOT NULL
    );
    
    CREATE TABLE RUTINA_EJERCICIO (
        ID_RUTINA_EJERCICIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        ID_RUTINA NUMBER(10) ,
        ID_EJERCICIO NUMBER(10) ,
        SERIES NUMBER(1) NOT NULL CHECK (SERIES BETWEEN 1 AND 9),
        REPETICIONES NUMBER(3) NOT NULL,
        DIA_SEMANA VARCHAR2(10) CHECK (DIA_SEMANA IN('LUNES','MARTES','MIÉRCOLES','JUEVES','VIERNES','SÁBADO')),
        
        CONSTRAINT FK_RUTINA_EJER_RUTINA FOREIGN KEY (ID_RUTINA)
        REFERENCES RUTINA(ID_RUTINA) ON DELETE CASCADE,
        CONSTRAINT FK_RUTINA_EJER_EJERCICIO FOREIGN KEY (ID_EJERCICIO)
        REFERENCES EJERCICIO(ID_EJERCICIO)
    );
    CREATE TABLE SALA(
        ID_SALA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR2(30)
    );
    
    CREATE TABLE CLASE(
        ID_CLASE NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NOMBRE VARCHAR2(30),
        DESCRIPCION VARCHAR2(100),
        FECHA_INICIO DATE, --NO QUEREMOS SACAR MAS TABLAS
        FECHA_FIN DATE,
        SALA NUMBER(10),
        
        CONSTRAINT FK_SALA FOREIGN KEY (SALA)
        REFERENCES SALA(ID_SALA)
    );
    
    CREATE TABLE MONITOR_CLASE(
        ID_MONITOR NUMBER(10),
        ID_CLASE NUMBER(10),
        
        CONSTRAINT FK_MONITOR_CLASE FOREIGN KEY (ID_MONITOR)
        REFERENCES MONITOR(ID_MONITOR),
        CONSTRAINT FK_CLASE_MONITOR FOREIGN KEY (ID_CLASE)
        REFERENCES CLASE(ID_CLASE)
    );


        -- 1. Obtener empleados con su información personal  
    SELECT P.NOMBRE, P.APELLIDO1, P.APELLIDO2, P.EMAIL, E.SALARIO, E.FECHA_CONTRATACION  
    FROM EMPLEADO E  
    JOIN PERSONA P ON E.DNI = P.DNI;  
    
    -- 2. Listar monitores con sus datos personales  
    SELECT P.NOMBRE, P.APELLIDO1, P.APELLIDO2, M.ID_MONITOR  
    FROM MONITOR M  
    JOIN EMPLEADO E ON M.ID_EMPLEADO = E.ID_EMPLEADO  
    JOIN PERSONA P ON E.DNI = P.DNI;  
    
    -- 3. Mostrar usuarios con sus rutinas asignadas  
    SELECT U.ID_USUARIO, P.NOMBRE, P.APELLIDO1, R.NOMBRE AS RUTINA  
    FROM USUARIO U  
    JOIN PERSONA P ON U.DNI = P.DNI  
    JOIN USUARIO_RUTINA UR ON U.ID_USUARIO = UR.ID_USUARIO  
    JOIN RUTINA R ON UR.ID_RUTINA = R.ID_RUTINA;  
    
    -- 4. Ver ejercicios dentro de cada rutina  
    SELECT R.NOMBRE AS RUTINA, E.NOMBRE AS EJERCICIO, RE.SERIES, RE.REPETICIONES, RE.DIA_SEMANA  
    FROM RUTINA_EJERCICIO RE  
    JOIN RUTINA R ON RE.ID_RUTINA = R.ID_RUTINA  
    JOIN EJERCICIO E ON RE.ID_EJERCICIO = E.ID_EJERCICIO;  
    
    -- 5. Mostrar clases con sus monitores  
    SELECT C.NOMBRE AS CLASE, M.ID_MONITOR, P.NOMBRE AS MONITOR  
    FROM MONITOR_CLASE MC  
    JOIN MONITOR M ON MC.ID_MONITOR = M.ID_MONITOR  
    JOIN EMPLEADO E ON M.ID_EMPLEADO = E.ID_EMPLEADO  
    JOIN PERSONA P ON E.DNI = P.DNI  
    JOIN CLASE C ON MC.ID_CLASE = C.ID_CLASE;  
    
    -- 6. Ver horarios de empleados  
    SELECT P.NOMBRE, P.APELLIDO1, H.TIPO AS TURNO  
    FROM HORARIO H  
    JOIN EMPLEADO E ON H.ID_EMPLEADO = E.ID_EMPLEADO  
    JOIN PERSONA P ON E.DNI = P.DNI;  

    
    
    
    